#!/bin/sh
# Idempotent per-host fleet convergence. Pull model: run me on a timer.
#   1. git pull the fir-exts package (re-exec if this script changed)
#   2. ensure the `. ~/sync/shared/fleet/env` stanza in ~/.profile and ~/.zshenv
#   3. render that env file into environment.d (Linux) / launchctl (macOS)
#   4. always write ~/sync/shared/fleet/status/<host>.status
# Silent and cheap when nothing changed. Safe to re-run.
set -eu

PKG_DIR="${FIR_FLEET_PKG_DIR:-$HOME/.config/fir/packages/git/github.com/kfet/fir-exts}"
FLEET_DIR="${FIR_FLEET_DIR:-$HOME/sync/shared/fleet}"
ENV_FILE="$FLEET_DIR/env"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
HOST=$(hostname -s 2>/dev/null || hostname)
STATUS="$FLEET_DIR/status/$HOST.status"
STANZA='[ -f "$HOME/sync/shared/fleet/env" ] && . "$HOME/sync/shared/fleet/env"'
LEGACY='export FIR_REMINDERS_STORE="$HOME/sync/shared/reminders"'
case "$(uname -s)" in Darwin) RENDERED="$CFG/fir-fleet/50-fleet.conf" ;;
                      *)      RENDERED="$CFG/environment.d/50-fleet.conf" ;; esac

reason='started'
finish() {
  rc=$?
  mkdir -p "$(dirname "$STATUS")" 2>/dev/null || true
  sha=$(git -C "$PKG_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)
  [ "$rc" -eq 0 ] && st=ok || st="FAIL $reason"
  printf '%s %s %s %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$HOST" "$sha" "$st" >"$STATUS"
}
trap finish EXIT

# 1. pull, and re-exec ourselves if this very script moved.
# NEVER `git pull`: it decides what to merge by reading FETCH_HEAD, which git
# rewrites non-atomically. fir itself runs `git fetch --tags origin` on this same
# clone at session start, so a concurrent fetch clobbers the FETCH_HEAD our pull
# is mid-read of — giving "Cannot fast-forward to multiple branches" (duplicated
# entries) or "no such ref was fetched" (lost entry). fetch + merge of the
# remote-tracking REF instead: ref updates are atomic, so a racing fetch can at
# worst leave us one commit behind, which the next run picks up.
reason='git fetch/merge failed'
me="$PKG_DIR/fleet/converge.sh"
before=$(cksum "$me" 2>/dev/null || echo none)
upstream=$(git -C "$PKG_DIR" rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null \
        || git -C "$PKG_DIR" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null \
        || echo origin/main)
git -C "$PKG_DIR" fetch --quiet origin
git -C "$PKG_DIR" merge --ff-only --quiet "$upstream"
if [ "${FIR_CONVERGE_REEXEC:-0}" != 1 ] && [ "$(cksum "$me" 2>/dev/null || echo none)" != "$before" ]; then
  echo "converge.sh changed — re-exec"; trap - EXIT; FIR_CONVERGE_REEXEC=1 exec "$me" "$@"
fi

# 2. shell stanza, exactly once per rc file; drop the legacy export we used to append
reason='rc file update failed'
for rc in "$HOME/.profile" "$HOME/.zshenv"; do
  [ -f "$rc" ] || : >"$rc"
  if grep -qxF "$LEGACY" "$rc"; then
    grep -vxF "$LEGACY" "$rc" >"$rc.fleet.tmp" && mv "$rc.fleet.tmp" "$rc"
    echo "removed legacy export from $rc"
  fi
  grep -qxF "$STANZA" "$rc" || { printf '%s\n' "$STANZA" >>"$rc"; echo "added fleet env stanza to $rc"; }
done

# 3. render env file -> expanded KEY=VALUE (only the vars it actually sets)
reason='env render failed'
[ -f "$ENV_FILE" ] || { echo "no $ENV_FILE — nothing to render"; exit 0; }
b=$(mktemp); f=$(mktemp); n=$(mktemp)
trap 'rm -f "$b" "$f" "$n"; finish' EXIT
env -i HOME="$HOME" USER="${USER:-}" sh -c 'env' | sort >"$b"
env -i HOME="$HOME" USER="${USER:-}" sh -c '. "$0"; env' "$ENV_FILE" | sort >"$f"
{ echo "# generated by fleet/converge.sh from $ENV_FILE — do not edit"
  comm -13 "$b" "$f" | grep -v '^_='; } >"$n"

changed=0
if [ ! -f "$RENDERED" ] || ! cmp -s "$n" "$RENDERED"; then
  mkdir -p "$(dirname "$RENDERED")"
  cp "$n" "$RENDERED"
  echo "rendered $RENDERED"
  changed=1
fi

# environment.d supersedes the old per-unit drop-in; remove only exactly that file
for d in "$CFG"/systemd/user/poe-acp-*.service.d; do
  [ -f "$d/reminders-store.conf" ] || continue
  rm -f "$d/reminders-store.conf"; rmdir "$d" 2>/dev/null || true
  echo "removed superseded drop-in $d/reminders-store.conf"
  changed=1
done

[ "$changed" = 1 ] || exit 0                 # converged; stay silent

# 3b. activate
reason='post-render activation failed'
if [ "$(uname -s)" = Darwin ]; then
  # no systemd: export into the launchd session. Already-running agents need a restart.
  grep -v '^#' "$RENDERED" | while IFS='=' read -r k v; do
    [ -n "$k" ] && launchctl setenv "$k" "$v"
  done
else
  systemctl --user daemon-reload 2>/dev/null || true
  for u in $(systemctl --user list-units --type=service --state=running \
             --plain --no-legend 'poe-acp*.service' 2>/dev/null | awk '{print $1}'); do
    systemctl --user restart "$u" && echo "restarted $u"
  done
fi
